### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by mikecoburn** [mikecoburn/furima-31000#10]
## URL
https://furima-31000.herokuapp.com/

## Basic認証
ID: furima
password: 1234

## メールアドレスとパスワード (出品者用)
mail: tama@sample.com
password: 123tama

## メールアドレスとパスワード (購入者用)
mail : pochi@sample.com
password : 123pochi

## 購入用テストカードの番号・期限・セキュリティコード(PAY.JP)
card : 4242424242424242
期限 : 12/2023　※未来であれば可
セキュリティコード : 123

**Comment by mikecoburn** [comment]
確認の程、よろしくお願いします。

**Comment by ayanasunakawa** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**商品詳細機能**
- [ ] ログアウトした状態でも、商品詳細ページを閲覧できるよう実装しましょう。
現在は、ログアウトしている状態で商品をクリックし、詳細ページに遷移しようとすると以下のエラーになってしまいます。

<img width="636" alt="スクリーンショット 2020-11-10 16 29 32" src="https://user-images.githubusercontent.com/54050089/98643207-014d0200-2372-11eb-8fa9-5e51795c976f.png">


修正次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mikecoburn** [comment]
確認しました。
ログアウト状態の判別が含まれていなかった様です。
修正を加えましたので、確認お願いします。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
